export const SampleData = [
  {
    id: 1,
    name: "Ava Martinez",
    area: "Upper West Side",
    profilePic: require("./assets/f1.png"),
    isSelected: false,
  },
  {
    id: 2,
    name: "Martin Thomson",
    area: "Upper West Side",
    profilePic: require("./assets/m1.png"),
    isSelected: false,
  },
  {
    id: 3,
    name: "Emma Johnson",
    area: "Upper West Side",
    profilePic: require("./assets/f2.png"),
    isSelected: false,
  },
  {
    id: 4,
    name: "Ethan Davis",
    area: "Upper West Side",
    profilePic: require("./assets/m2.png"),
    isSelected: false,
  },
  {
    id: 5,
    name: "Isbella Wright",
    area: "Upper West Side",
    profilePic: require("./assets/f3.png"),
    isSelected: false,
  },
  {
    id: 6,
    name: "Micheal Reodicurz",
    area: "Upper West Side",
    profilePic: require("./assets/m3.png"),
    isSelected: false,
  },
  {
    id: 7,
    name: "Mia Scott",
    area: "Upper West Side",
    profilePic: require("./assets/f4.png"),
    isSelected: false,
  },
  {
    id: 8,
    name: "John Walker",
    area: "Upper West Side",
    profilePic: require("./assets/m4.png"),
    isSelected: false,
  },
  {
    id: 9,
    name: "Lara Thomson",
    area: "Upper West Side",
    profilePic: require("./assets/f5.png"),
    isSelected: false,
  },
  {
    id: 10,
    name: "David Cool",
    area: "Upper West Side",
    profilePic: require("./assets/m5.png"),
    isSelected: false,
  },
  // Add more data as needed
];
